import os
import sys
import json
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env
base_dir = Path(__file__).resolve().parent
load_dotenv(dotenv_path=base_dir / ".env")

# Import Member 2's verified module
from src.stage1_analysis import analyze_user_request

# Import Member 3's module if available; otherwise use local fallback for testing
try:
    from src.stage2_plan import generate_actionable_response
except ImportError:
    generate_actionable_response = None

# Import Member 5's logging utility if available
try:
    from src.utils import save_conversation
except ImportError:
    save_conversation = None


def load_processed_knowledge() -> str:
    """Reads all processed text files generated by Member 1's parser."""
    processed_dir = base_dir / "data" / "processed"
    if not processed_dir.exists():
        return "No knowledge base found."

    text_contents = []
    for txt_file in processed_dir.rglob("*.txt"):
        try:
            content = txt_file.read_text(encoding="utf-8")
            text_contents.append(f"--- SOURCE: {txt_file.name} ---\n{content}")
        except Exception as e:
            continue

    return "\n\n".join(text_contents)


def fallback_stage2_response(user_query: str, analysis: dict) -> str:
    """Provides a structured response using Stage 1 analysis if stage2_plan.py is not yet merged."""
    cat = analysis.get("inquiry_category", "General Information")
    amount = analysis.get("target_amount", 0)
    status = analysis.get("membership_status", "Unknown")
    urgency = analysis.get("detected_urgency", "Low")
    vars_ext = analysis.get("key_variables_extracted", "")

    response = f"### RUPSA SACCO Assistant\n\n"
    response += f"**Category:** {cat}\n"
    response += f"**Membership Status:** {status}\n"
    if amount > 0:
        response += f"**Requested Amount:** KES {amount:,}\n"
    response += f"**Urgency:** {urgency}\n\n"
    response += f"**Summary:** {vars_ext}\n\n"
    response += f"Thank you for contacting RUPSA SACCO. Your query regarding {cat.lower()} has been received and flagged for processing."
    return response


def run_cli():
    """Main execution loop for the RUPSA SACCO CLI Assistant."""
    print("=" * 65)
    print("             RUPSA SACCO VIRTUAL ASSISTANT CLI")
    print("=" * 65)
    print("Type your inquiry below, or type 'exit' or 'quit' to stop.\n")

    while True:
        try:
            user_input = input("\nUser Query > ").strip()
        except (KeyboardInterrupt, EOFError):
            print("\nExiting assistant. Goodbye!")
            break

        if not user_input:
            print("⚠️ Please enter a valid question.")
            continue

        if user_input.lower() in ["exit", "quit"]:
            print("\nThank you for using RUPSA SACCO Virtual Assistant. Goodbye!")
            break

        # Step 1: Execute Stage 1 Analysis (Member 2)
        print("\n[1/2] Analyzing query structure (Stage 1)...")
        try:
            raw_json_str = analyze_user_request(user_input)
            analysis_dict = json.loads(raw_json_str)
            print("✓ Stage 1 completed successfully.")
        except Exception as e:
            print(f"❌ Error during Stage 1 execution: {e}")
            continue

        # Step 2: Execute Stage 2 Response Generation (Member 3 or Fallback)
        print("[2/2] Generating response (Stage 2)...")
        if generate_actionable_response:
            try:
                final_response = generate_actionable_response(user_input, analysis_dict)
            except Exception as e:
                print(f"⚠️ Stage 2 module failed: {e}. Switching to fallback response.")
                final_response = fallback_stage2_response(user_input, analysis_dict)
        else:
            final_response = fallback_stage2_response(user_input, analysis_dict)

        # Step 3: Display Output
        print("\n" + "=" * 65)
        print(final_response)
        print("=" * 65)

        # Step 4: Save Log (Member 5)
        if save_conversation:
            try:
                save_conversation(user_input, analysis_dict, final_response)
            except Exception:
                pass


if __name__ == "__main__":
    run_cli()